### ISSUE TITLE
CMKD on nuscenes dataset

### ISSUE THREAD

**Issue by charmeleonz** [Cc-Hy/CMKD#31]
Hi, does CMKD support training and testing on nuscenes dataset? What should be used as labelled and unlabelled data in the case of nuscenes dataset? Thanks!

**Comment by Cc-Hy** [comment]
Hi, 
We provide an implementation for nuscnenes based on mmdet3d at [this link](https://github.com/Cc-Hy/CMKD-MV).
Currently, we use the labeled samples for both teacher model training and student model training, and we have not done experiments related to unlabeled samples. You can have a try if you are interested. 
For example, there is unlabeled sweep data between the labeled key frames. But I think it might not be very helpful to the performance because the sweep data are very alike the labeled samples.

**Comment by charmeleonz** [comment]
Ok thanks!
